services:
  app-server:
    build:
      context: ./app-server
      target: production
    tty: true
    restart: always
    working_dir: /opt/server
    volumes:
      - ./app-server:/opt/server
      - ./static:/opt/static
      - /opt/server/node_modules/
      - /opt/server/dist/
    env_file:
      - .env
    expose:
      - '3000'
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always

  nginx:
    depends_on:
      - app-server
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - '80'
    restart: always
volumes:
  postgres-data: